### PR TITLE
Version 1.0 BETA

### PR DESCRIPTION
**Pull request by Victorb101**
Created board, schematic, gerbers, and BOM.

### CODE REVIEW

**Comment by aaronbeekay** [comment]
Issues:

* BOM format incorrect
* Doesn't this need to plug into the Kvaser?
* Wiki page should be updated with connector list and other info

**Comment by Victorb101** [comment]
@aaronbeekay Review for BETA

**Comment by Victorb101** [comment]
@aaronbeekay Review for Version 1.0?

**Comment by aaronbeekay** [comment]
@Victorb101:

* I think lines on "Dimension" should be zero-width
* Font on .brd should be "Vector"
* Again, multiple .sch and .brd files -- do you have a script that's doing this or something?
* BOM format wrong
* Need .brd PDFs

* The "SHIELD_GND" pins on the Micro-Fit CAN connectors should be tied to GND

**Comment by Victorb101** [comment]
@aaronbeekay Good to go

**Comment by aaronbeekay** [comment]
@Victorb101 The text labels for your board are on layers 121 and 122, not 21 and 22 -- is this intentional? It will break when using the team's CAM job.

**Comment by aaronbeekay** [comment]
@Victorb101 I fixed the silk issues and regenerated CAM files/PDFs. Your libraries were also out of date JFYI, which is what caused the PDFs to be generated weird

**Pull request merged**
